export const descriptors = [
  'Forest',
  'Ancient',
  'Petrified',
  'Roaring',
  'Cascade',
  'Tumbling',
  'Silent',
  'Redwood',
  'Bullfrog',
  'Maple',
  'Misty',
  'Elk',
  'Grizzly',
  'Ocean',
  'Sea',
  'Sky',
  'Dusty',
  'Diamond',
];

export const places = [
  'Flats',
  'Village',
  'Canyon',
  'Pond',
  'Group Camp',
  'Horse Camp',
  'Ghost Town',
  'Camp',
  'Dispersed Camp',
  'Backcountry',
  'River',
  'Creek',
  'Creekside',
  'Bay',
  'Spring',
  'Bayshore',
  'Sands',
  'Mule Camp',
  'Hunting Camp',
  'Cliffs',
  'Hollow',
];

export const descriptions = [
  'Tucked away among towering redwoods, this secluded campground offers the perfect spot for tent and RV camping. Enjoy the peace and tranquility of the forest while still being close to the amenities you need for a comfortable stay.',
  "With picturesque views of a crystal-clear mountain lake, this campground is an angler's paradise. Cast your line and try your luck at catching the big one, or simply take in the breathtaking scenery as you relax on the shore.",
  'Hikers and nature enthusiasts will love this campground, set deep in the heart of the Rocky Mountains. Take a hike on one of the many trails and discover the beauty and wonder of the mountains, or simply sit back and enjoy the view.',
  "Escape to the tropical paradise of this forested campground for a relaxing getaway. Surrounded by lush vegetation, it's the perfect spot to unwind and reconnect with nature.",
  "Unforgettable views await at this campground, located on the edge of one of the world's most iconic natural wonders. Whether you're here for the stunning vistas, the abundance of outdoor activities or just to experience the wonder of it all, this campground has it all.",
  'Spend your days fishing, swimming, and tubing at this campground, set on the banks of a meandering river. With the peaceful sound of the water in the background, and the natural beauty all around, this campground is the perfect place to relax and enjoy the great outdoors.',
  'Nestled in the heart of the Great Smoky Mountains, this campground offers a peaceful escape from the hustle and bustle of everyday life. Enjoy the natural beauty of the mountains, and take a hike on one of the many trails that wind through the area.',
  'Experience the unique beauty of the Sonoran Desert at this campground. With easy access to hiking trails, and plenty of opportunities for stargazing, this is the perfect spot for anyone who wants to explore the great outdoors.',
  'Located in the Appalachians, this campground offers easy access to hiking trails and scenic vistas. Take a hike and discover the natural beauty of the area, or simply sit back and enjoy the view from your campsite.',
  'This campground, located on the banks of a pristine mountain stream, is the perfect spot for a relaxing getaway. Take a dip in the cool, clear water, or simply sit back and listen to the gentle sound of the stream as you relax in the great outdoors.',
  "Located in the Adirondack Mountains, this campground offers easy access to hiking trails and excellent fishing opportunities. Whether you're an experienced hiker or just looking for a relaxing getaway, this campground has something for everyone.",
  'This campground, surrounded by lush tropical forests, is the perfect spot for a relaxing getaway. Take a hike through the forest, or simply sit back and relax in the natural beauty of the area.',
  'Located on the shores of a sparkling lake, this campground offers excellent swimming and boating opportunities. Take a dip in the lake, or rent a boat and explore the area from a different perspective.',
  'Located in the Sierra Nevada Mountains, this campground offers easy access to hiking trails and breathtaking views. Take a hike and discover the natural beauty of the area, or simply sit back and enjoy the view from your campsite.',
  'This campground, located in the Ozarks, offers a peaceful escape from the hustle and bustle of everyday life. Take a hike on one of the many trails and discover the natural beauty of the area, or simply relax by the river and enjoy the tranquility of the wilderness',

  'Located in the heart of the Cascades, this campground offers easy access to hiking trails and scenic vistas. Take a hike and discover the natural beauty of the area, or simply sit back and enjoy the view from your campsite.',
  'This campground, nestled in a secluded valley, offers a peaceful escape from the hustle and bustle of everyday life. Take a hike on one of the many trails and discover the natural beauty of the area, or simply relax by the stream and enjoy the tranquility of the wilderness.',
  'Located on the coast, this campground offers easy access to the beach and excellent opportunities for swimming, fishing, and boating. Take a dip in the ocean, or rent a kayak and explore the area from a different perspective.',
  'Nestled in the heart of the Poconos, this campground offers a peaceful escape from the hustle and bustle of everyday life. Take a hike on one of the many trails and discover the natural beauty of the area, or simply relax by the lake and enjoy the tranquility of the wilderness.',
  'Located in the heart of the White Mountains, this campground offers easy access to hiking trails and scenic vistas. Take a hike and discover the natural beauty of the area, or simply sit back and enjoy the view from your campsite.',
];
